Support "latest" release in "install-tekton-release"
Add support for installing "latest", which is also now the default
value for the version paramter.

diff --git a/tekton/resources/release/install_tekton_release.yaml b/tekton/resources/release/install_tekton_release.yaml
--- a/tekton/resources/release/install_tekton_release.yaml
+++ b/tekton/resources/release/install_tekton_release.yaml
@@ -33,6 +33,7 @@ spec:
       default: tekton-pipelines
     - name: version
       description: The vX.Y.Z version that we want to install (including `v`)
+      default: latest
     - name: default-service-account
       description: Service account to be setup as default in Tekton configmap
       default: default
@@ -50,34 +51,38 @@ spec:
       #!/usr/bin/env bash
       set -exo pipefail
 
-      OVERLAY_ROOT=$(inputs.params.projectName)/overlays/$(inputs.params.environment)
-      RELEASE_ROOT=$(inputs.resources.release-bucket.path)/previous/$(inputs.params.version)
+      KUBECONFIG=/workspace/$(inputs.resources.k8s-cluster.name)/kubeconfig
+      # Set up RELEASE_ROOT
+      if [[ "$(inputs.params.version)" == "latest "]]; then
+        RELEASE_ROOT=$(inputs.resources.release-bucket.path)/$(inputs.params.version)
+      else
+        RELEASE_ROOT=$(inputs.resources.release-bucket.path)/previous/$(inputs.params.version)
+      fi
+
+      # Handle Overlays
+      OVERLAY_FOLDER=$(inputs.params.projectName)/overlays/$(inputs.params.environment)
+      APPLY_MODE="-k $OVERLAY_FOLDER"
 
       cd $(inputs.resources.plumbing-library.path)/tekton/cd
 
       if [ ! -d $(inputs.params.projectName) ]; then
         # There are is not base or project for $(inputs.params.projectName)
         # Apply the release as is
-        kubectl apply \
-          --filename $RELEASE_ROOT/$(inputs.params.release-file) \
-          --kubeconfig /workspace/$(inputs.resources.k8s-cluster.name)/kubeconfig
+        APPLY_MODE="--filename $RELEASE_ROOT/$(inputs.params.release-file)"
       else
-          # If the base exists, an overlay for the specified environment must exist
-          if [ ! -d  "$OVERLAY_ROOT" ]; then
-            echo "Environment $(inputs.params.environment) not found for project $(inputs.params.projectName)"
-            exit 1
-          fi
-          cp $RELEASE_ROOT/$(inputs.params.release-file) $(inputs.params.projectName)/base/release.yaml
-          find .
+        # If the base exists, an overlay for the specified environment must exist
+        if [ ! -d  "$OVERLAY_FOLDER" ]; then
+          echo "Environment $(inputs.params.environment) not found for project $(inputs.params.projectName)"
+          exit 1
+        fi
+        cp $RELEASE_ROOT/$(inputs.params.release-file) $(inputs.params.projectName)/base/release.yaml
+        find .
 
-          # Execute pre-deploy scripts if any
-          scripts=$(find ${OVERLAY_ROOT}/pre -name '*.sh' 2> /dev/null || true)
-          for script in $scripts; do $script; done
-
-          kubectl apply \
-            --kubeconfig /workspace/$(inputs.resources.k8s-cluster.name)/kubeconfig \
-            -k $(inputs.params.projectName)/overlays/$(inputs.params.environment)
+        # Execute pre-deploy scripts if any
+        scripts=$(find ${OVERLAY_FOLDER}/pre -name '*.sh' 2> /dev/null || true)
+        for script in $scripts; do $script; done
       fi
+      kubectl apply --kubeconfig $KUBECONFIG $APPLY_MODE
 
   - name: wait-until-pods-running
     image: gcr.io/tekton-releases/dogfooding/ko:gcloud-latest
